server:
  port: 8080

spring:
  system:
    path: " "
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/doorsensor?characterEcoding=UTF-8&useSSL=False&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update